// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_distance
arma::mat cpp_distance(arma::mat& X);
RcppExport SEXP _exp3riment_cpp_distance(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_distance(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_effective
arma::mat cpp_effective(arma::mat& X);
RcppExport SEXP _exp3riment_cpp_effective(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_effective(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_effective_sym
arma::mat cpp_effective_sym(arma::mat& A);
RcppExport SEXP _exp3riment_cpp_effective_sym(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_effective_sym(A));
    return rcpp_result_gen;
END_RCPP
}
// src_standard_kernel
Rcpp::List src_standard_kernel(arma::mat& D, arma::uword nbdk, double alpha);
RcppExport SEXP _exp3riment_src_standard_kernel(SEXP DSEXP, SEXP nbdkSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nbdk(nbdkSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(src_standard_kernel(D, nbdk, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exp3riment_cpp_distance", (DL_FUNC) &_exp3riment_cpp_distance, 1},
    {"_exp3riment_cpp_effective", (DL_FUNC) &_exp3riment_cpp_effective, 1},
    {"_exp3riment_cpp_effective_sym", (DL_FUNC) &_exp3riment_cpp_effective_sym, 1},
    {"_exp3riment_src_standard_kernel", (DL_FUNC) &_exp3riment_src_standard_kernel, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_exp3riment(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
