# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_distance <- function(X) {
    .Call('_exp3riment_cpp_distance', PACKAGE = 'exp3riment', X)
}

cpp_effective <- function(X) {
    .Call('_exp3riment_cpp_effective', PACKAGE = 'exp3riment', X)
}

src_standard_kernel <- function(D, nbdk, alpha) {
    .Call('_exp3riment_src_standard_kernel', PACKAGE = 'exp3riment', D, nbdk, alpha)
}

